name: meloplay
description: 'Meloplay is a local music player app that plays music from your device built with Flutter.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.3

environment:
    sdk: '>=3.3.4 <4.0.0'

dependencies:
    bloc: ^8.1.4 # state management
    flutter:
        sdk: flutter # flutter sdk
    flutter_bloc: ^8.1.5 # state management
    flutter_cache_manager: ^3.3.2
    flutter_staggered_animations: ^1.1.1 # animation
    fluttertoast: ^8.2.5
    get_it: ^7.7.0 # dependency injection
    hive: ^2.2.3 # local database
    hive_flutter: ^1.1.0 # local database
    just_audio: ^0.9.37 # audio player
    just_audio_background: ^0.0.1-beta.11 # audio player background
    lottie: ^3.1.0
    marquee: ^2.2.3
    on_audio_query: ^2.9.0 # get songs from device
    package_info_plus: ^8.0.0 # get app info
    permission_handler: ^11.3.1 # get permission
    rxdart: ^0.27.7 # stream
    share_plus: ^9.0.0 # share song
    url_launcher: ^6.2.6 # open url

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.2 # linter
    flutter_launcher_icons: ^0.13.1 # app icon generator

flutter:
    uses-material-design: true
    assets:
        - assets/icon/
        - assets/lottie/
        - assets/images/

flutter_launcher_icons:
    image_path: 'assets/icon/icon.png'
    android: true
    ios: true
# dart pub get
# dart run flutter_launcher_icons
